languageCode = "en-us"
title = "Aerial"
baseurl = "http://example.org/"
theme = "aerial"

[params]
  name = "Jenell Pizarro"
  about = "Front End Developer &nbsp;&bull;&nbsp; Cyborg &nbsp;&bull;&nbsp; Never asked for this"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/nellarro"

[[params.social]]
  medium = "phone"
  icon = "phone"
  link = "tel:555-555-555"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/nellarro"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "mailto:nellarro@gmail.com?subject=You%20Seem%20Like%20A%20Nifty%20Dev&body=Let's%20chat!"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://github.com/nellarro"